app = "fisiorely-aip"

kill_signal = "SIGINT"
kill_timeout = 5



[build]
  builder = "heroku/buildpacks:20"

[[services]]
  http_checks = []
  http_port = 3000

  [[services.concurrency]]
    hard_limit = 10
    soft_limit = 5

  [[services.ports]]
    port = "3000"
