app = "fisiorely-api"

[build]
  dockerfile = "Dockerfile"

[env]

  PORT = "8080"

 [[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = "8080"

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000

